import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CssBaseline, InitColorSchemeScript, ThemeProvider } from "@mui/material";

import { Sidebar } from "@/components/sidebar";
import { theme } from "@/theme";

export const metadata: Metadata = {
  title: "NextJS MUI Form",
  description: "Generated by NextJS MUI Form",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Sidebar />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
