import { Box, CssBaseline, InitColorSchemeScript, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";

import { Sidebar } from "@/components/sidebar";
import { Topbar } from "@/components/topbar";
import { theme } from "@/theme";

export const metadata: Metadata = {
  title: "NextJS MUI Form",
  description: "Generated by NextJS MUI Form",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Box sx={{ display: "flex" }}>
              <Sidebar />
              <Box component={"main"} sx={{ flexGrow: 1, bgcolor: "primary.main" }}>
                <Topbar />
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
