import { Box, CssBaseline, InitColorSchemeScript, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";

import { Sidebar, Topbar } from "@/components";
import { NotificationProvider } from "@/context/notification-provider";
import { theme } from "@/theme";

export const metadata: Metadata = {
  title: "NextJS MUI Form",
  description: "Generated by NextJS MUI Form",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <NotificationProvider>
              <Box sx={{ display: "flex", position: "relative" }}>
                <Sidebar />
                <Box component={"main"} sx={{ flexGrow: 1, bgcolor: "primary.main", minHeight: "100vh" }}>
                  <Topbar />
                  {children}
                </Box>
              </Box>
            </NotificationProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
